remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: AntSync
# description: 文件同步工具, 支持OSS、FTP、WebDav等云端

show_downloads: false

github:
  zip_url: https://www.github.com/jiangmitiao/AntSync/releases
  tar_url: https://www.github.com/jiangmitiao/AntSync/tags

# theme: jekyll-theme-cayman
